* résultats
** France
- MS : 2010% -> 2022%
- DA : Valeur en 2022 de base 100 2010
- uv : valeur en 2022 de base 100 2010
- HP : valeur en 2022 de base 100 2010
  
| Secteur      | MS         |  DA |   uv |  HP |
| Chaussures   | 3% -> 7%   | 144 |  137 |  54 |
| Habillement  | 6% -> 6%   |  60 |  143 |  71 |
| Maroquinerie | 29% -> 37% | 215 | 1209 | 172 |
| Bijouterie   | 12% -> 6%  | 253 |  322 |  28 |

** Italie
- MS : 2010% -> 2022%
- DA : valeur en 2022 de base 100 2010 // ratio France
- uv : valeur en 2022 de base 100 2010 // ratio France
- HP : valeur en 2022 de base 100 2010 // ratio France

| Secteur      | MS         | DA          | uv          | HP         |
| Chaussures   | 9% -> 27%  | 140 // 0.98 | 308 // 2    | 70 // 1.3  |
| Habillement  | 10% -> 17% | 53 // 0.87  | 150 // 1.05 | 76 // 1.08 |
| Maroquinerie | 26% -> 31% | 298 // 1.38 | 139 // 0.11 | 103 // 0.6 |
| Bijouterie   | 7% -> 8%   | 166 // 0.65 | 177 // 0.55 | 110 // 3.9 |

** Chine et Hong Kong

- MS : 2010% -> 2022%
- DA : valeur en 2022 de base 100 2010 // ratio France
- uv : valeur en 2022 de base 100 2010 // ratio France
- HP : valeur en 2022 de base 100 2010 // ratio France

| Secteur      | MS         | DA          | uv          | HP          |
| Chaussures   | 33% -> 18% | 72 // 0.5   | 179 // 1.3  | 559 // 10.4 |
| Habillement  | 25% -> 17% | 24 // 0.4   | 149 // 1.04 | 225 // 3    |
| Maroquinerie | 7% -> 3%   | 417 // 1.97 | 222 // 0.18 | 443 // 2.6  |
| Bijouterie   | 13% -> 16% | 221.5 // 08 | 62 // 0.19  | 97 // 3.4   |

** Reste de l'Asie
- MS : 2010% -> 2022%
- DA : valeur en 2022 de base 100 2010 // ratio France
- uv : valeur en 2022 de base 100 2010 // ratio France
- HP : valeur en 2022 de base 100 2010 // ratio France

| Secteur      | MS         | DA          | uv          | HP          |
| Chaussures   | 13% -> 14% | 103 // 0.71 | 119 // 0.86 | 113 // 2.1  |
| Habillement  | 22% -> 20% | 33 // 0.55  | 154 // 1.08 | 288 // 4.05 |
| Maroquinerie | 10% -> 11% | 235 // 1.1  | 233 // 0.19 | 14 // 0.08  |
| Bijouterie   | 8% -> 22%  | 800 // 3.15 | 200 // 0.62 | 58 // 2     |


** Reste de l'UE
- MS : 2010% -> 2022%
- DA : valeur en 2022 de base 100 2010 // ratio France
- uv : valeur en 2022 de base 100 2010 // ratio France
- HP : valeur en 2022 de base 100 2010 // ratio France

| Secteur      | MS         | DA           | uv            | HP           |
| Chaussures   | 19% -> 18% | 169 // 1.18  | 105 // 0.76   | 73.8 // 1.3  |
| Habillement  | 18% -> 23% | 47.5 // 0.79 | 144 // 1      | 56.6 // 0.8  |
| Maroquinerie | 15% -> 11% | 254 // 1.18  | 280 // 0.23   | 58,6 // 0.34 |
| Bijouterie   | 20% -> 6%  | 314 // 1.24  | 164.5 // 0.51 | 47.5 // 1.7  |



* Principaux faits
** Direction des exportations
*** Chaussures
Pour la France les pays europens représentent 51% de ses exportations et ses principaux partenaires sont le reste de l'UE avec 39%. On remarque cependant une baisse de la part des pays européens depuis 2016 au profit de la Chine et des USA surtout. Les USa (15%) et la Chine (13%) sont les deuxièmes et troisièmes partenaires commerciaux de la France.

La Chine commerce surtour avec les USa, le RDM et le reste de l'Asie et de l'UE.

Les pays européens représentent 43% des exportations de l'Italie et les pays du reste de l'UE sont les premiers partenaires devant les USA et la France. La Chine représente seulement 8% des exportations italiennes. 

*** Habillement
Les exportations de la France vers les pays européens représentent 39% des exportations françaises. Cette part à diminuée de plus de 10 points de pourcentage depuis 2010, aux profits nottament de la Chine et des USA. Après le reste de l'UE (27%), la Chine (18%) et les USA (12%) sont les principaux partenaires de la France.

La part des pays européens dans les exportations italiennes est de 44%. Les USa (14) et la Chine (12%) sont les principaux partenaires de l'Italie derrière le reste de l'UE. La part des pays européens à baisser depuis 2010 au profit de la Chine et des USA. 

*** Maroquinerie
Les pays européens représentent seulement 24% des exportations françaises. Le principal partenaire est la Chine avec 29% puis les USA avec 15%.

Pour la CHine on remarque que les USA étaient au début des années 2010 un parteniare majeur de la Chine. Mais ils ne représentent presque plus rien ajd. La Chine_KG commerce majoritairement au sein de sa  zone.

Pour l'Italie le constat est prsque le même que pour la France avec une part plus importante des exportations qui vont vers les pays européens. 

*** Bijouterie
La France exporte près de 60% de ses bijoux aux pays européens, dont la plus grande partie va vers la Suisse (36% des exportations fr). Le troisième partenaire de la France est la Chine avec 13%.

Près de 60% des échanges de la Chine_KG se fait entre ces deux pays. Le reste de leurs partaires sont les USA (10%) et le reste de l'Asie 7%.

Pour l'Italie, les pays européens représentent seulement 37% de leurs exportations. Ses principaux partenaires sont le RDM (17%), le rete de l'UE (16%), les USa (13%) et les ARE (12%).

** Parts de marché
*** Chaussures
Valeur commerciale a augmenté (forte chutte entre 2010 et 2013, rattrapage instantanné).
Baisse nottament causée par le reste des pays de l'UE et la Chine. 
Part de marché de la France qui augmente de 4 points de % principalement pendant la période de baisse du commerce. Globalement c'est les paus européens qui ont gagné pendant cette période.
Le vrai gagnant est l'Italie qui a augmenté drastiquement ses parts de marché pendant cette période de baisse puis à continuer de les augmenter au fil du temps.

*** Habillement
Le commerce des vêtements haut de gamme est en déclin depuis 2010. Forte baisse en 2014, instantannément compensée. Cette baisse est principalement causée par le reste des pays européens et l'Asie.
La part de marché de la France est restée stable sur toute la période (diminution du commerce en valeur). l'Italie quant à elle voit ses parts de marché encore augmenter avec une valeur commerciale qui semble rester stable.Le reste de l'UE voit ses parts de marché augmenter de manière relativement régulière depuis 2015 principalement. 
La Chine perd fortement des parts de marché surtout à partir de 2016, mais la baisse s'ammorce dès 2010.
Le reste de l'Asie perd quelques points de pourcentages de parts de marché.

*** Maroquinerie
Le commerce de la maroquinerie haut de gamme n'a fait qu'augmenter au fil des ans et la France en est la principale gagnante avec L'Italie. Bien que les parts de marché du reste de l'Asie soient relativement stables, la Chine déjà un acteur relativement peu important dans ce secteur (son secteur où elle pèse le moins), voit ses parts de marché très fortement diminuer vers 2016. Le reste des pays européens voit également son importance diminuer.

*** Bijouterie
Le secteur de la bijouterie a vu son commerce largement augmenté en 2010/2011 puis à partir de 2020 après une baisse en 2019 comparé à 2018. La France a perdu 2/3 de ses parts de marché en 2011. Depuis elle en regagne, mais reste faible sur ce secteur.
L'Italie n'a pas spécialement profité de cette augmentation du commerce. C'est l'Asie qui en ressort la grande gagnante au détriment du reste des pays européens et de la Suisse.

** Demande adressée
La demande adressée de la France augmente sur tous les secteurs hormis l'habillement. La demande adressée pour la bijouterie est celle qui a la plus grande augmentation par rapport à 2010 bien que cela diminu ces dernières années. Le secteur de la maroquinerie voit sa DA fortement augmenter depuis 2020. C'est surtout vers 2014 que les chaussures voient leur DA augmenter. La baisse de la DA de l'hbaillement a principalement lieu entre 2010 et 2016. Depuis elle est plutôt stable.

*** Chaussures
Sur le secteur des chaussures, seules la Suisse et le reste de l'UE ont enregistré une augmentation plus importante de leur demande adressée que la France. La Chine et le Moyen-Orient ont subi un fort décrochage de la croissance de leur DA par rapport à la France, principalement entre 2010 et 2014. La croissance de la Da de l'Italie a été inférieure à celle de la France jsuqu'en 2020 puis a rattrapée celle de la France et se situe désormais au même niveau. 

*** Habillement
Pour l'habillement, seule la SUisse dispose d'une croisssance de DA supérieure à celle de la France. L'Iatlie enregistre une croissance moindre mais assez proche tout de même. La Chine voit l'écart entre sa croissance et celle de la France augmenter chaque année.

*** Maroquinerie
Tous les pays ont vu la croissance de leur DA être plus importante que celle de la France. La Chine est le pays avec qui l'écart s'est le plus creusé, de même que la Suisse et l'Italie.

*** Bijouterie
La Suisse ainsi que le reste de l'Asie enregistrent une croissance bien plus importante de leur DA que celle de la France (nottament en 2011). La croissance de la DA de l'Italie est plus faible que celle de la France.

** Valeurs unitaires
Les valeurs unitaires françaises ont toutes augmenté par rapport à 2010. La maroquinerie enregistre depuyis 2018 une hausse incroyable de ses valeurs unitaires.

*** Chaussures
La croissance des valeurs unitaires de l'Iatlie est désormais bien plus grande que celle de la France bien que cela ait été l'inverse jusqu'en 2018. Parmis les croissances de valeurs unitaires les plus forte on retrouve la SUisse, le MO ainsi que la Chine bien que l'écart se soit réduit avec le temps.

En valeurs nominales, les valeurs unitaires de la France sont assez faibles et proche du niveau du reste de l'UE. La Chine et le Moyen-Orient ont les valeurs unitaires les plus basses, tandis que l'Iatlie et la Suisse ont les valeurs unitaires les plus élevées de très loin. 

*** Habillement
Hormis la Suisse, toutes les régions ont enregistrées une croissance de leurs valeurs unitaires plus élevées que celle de la France, avec le Moyen-Orient qui a l'écart le plus grand de loin.

La Suisse, l'Italie et la France ont les valeurs unitaires les plus élevées suivi par le reste de l'UE. La Chine et le reste de l'Asie sont les régions avec les valeurs unitaires les plus faibles.

*** Maroquinerie
Seule la Suisse a connu une croissance de ses valeurs unitaires plus grande que la France. Mais cet écart s'est réduit à presque rien depuis 2018 avec la très forte augmentation des valeurs unitaires françaises.

En 2010 la France était le deuxième pays avec les valeurs unitaires les plus élevées, mais alrgement derrière l'Italie. En 2022, La France dispose de très loin des valeurs unitaires les plus élevées suivi par l'Italie et la SUisse qui a vu ses valeurs unitaires croitre très fortement (elle était la ragion avec les valeurs unitaires les plus faibles). La Chine est la région avec les valeurs unitaires les plus faibles.

*** Bijouterie
Hormis la Suisse, aucun pays n'a enregistré de croissance des valeurs unitaires plus élevées que la France. Pour la Suisse ce rattrapage a lieu uniquement en 2022. La Suisse et les USA sont ceux avec qui le décrochage est le plus fort. L'Italie avait un fort décrochage maius rattrape la croissance des valeurs unitaires frnaçaises depuis 2020.

En niveau, c'est la Suise suivie du Moyen-Orient d'assez loin qui ont les valeurs unitaires les plus élevées. La FRance et l'Italie arrivent ensuite avec un petit écart entre eux mais loin des deux premiers. La Chine est la région qui pratique les valeurs unitaires les plus basses. Elle est également la seule région à avoir diminué ses valeurs unitaires.

** Hors-prix
La compétitivité hors-prix de la France a diminué pour tous les secteurs sauf pour la maroquinerie. Poru tous les secteurs la baisse est assez tendancielle année après année. Pour la maroquinerie, elle a très fortement augmenté à partir de 2012 puis a diminué de 2017 à 2019 repassant sous son niveau de 2010 avant d'augmenter fortement jusqu'en 2022.

*** Chaussures
La Chine a connu une augmentation presque continue et forte de sa compétitivité hors-prix comparée à la FRance. Il en va de même pour la SUisse mais l'écart s'est fortement réduit depuis 2018. La (dé)croissance de la compétitivité hors-prix de l'Italie est très similaire à celle de la France, tout comme le reste de l'UE.

Hormis la Chine et le reste de l'Asie toutes les régions ont connu une baisse de leur compétitivité hors-prix. L'amérique, preoère en 2010 est aujourd'hui très faible. En 2022, la France se retrouve derrière l'Italie et la Chine en terme de compétitivité hors-prix.

*** Habillement
Sur l'habillement, tous les pays sauf la les pays européens ont connu une croissance de leur hors-prix plus forte que celle de la France. Pour les pays européens, la décroissance est très similaire.

Les pays européens sont les seuls à avoir perdu de la compétitivité hors-prix. Le Moyen-Orient ainsi que l'Asie ont connu les croissances les plus fortes comparé à la France. Aujourd'hui l'Amérique a plus de hors-prix que les pays européens hormis la Suisse. Mais les pays europens restent les pays avec le plus de hors-prix, suivis de loin par la Chine.

*** Maroquinerie
Aujoud'hui la croissance du hors-prix de tous les pays sauf la Chine est très similaire et légèrement inférieure à celle de la France. Cela a toujours été le cas sauf entre 2018 et 2020, qui correspond à la période de forte baisse du hors prix en forte. On observe à cette période un fort décrochage de la France.

Tous les pays sauf le reste de l'Asie, le reste de l'Ue et le moyen-orient ont augmenté leur compétitivité hors-prix entre 2010 et 2022. La France était derrière la Suisse et l'Italie en 2010 est aujourd'hui légèrement devat la Suisse et loin devant l'Italie qui est elle même très loin devant l'Amérique. La Chine et le reste de l'Asie sont ceux avec kles plus faibles compétitivités hos-prix.

*** Bijouterie
Pour la bijouterie, toutes les régions observent une croissance de leur hors-prix plus importante que celle de la France avec la Suisse et le MOyen-Orient qui sotn ceux qui décrochent le plus la France.

Seuls les USA, le Moyen-Orient, la Suisse et l'Italie ont réussi à augmenter leur hors-prix entre 2010 et 2022. La France était le troisième pays derrière la Suisse et les USA, mais aujourd'hui elle se retrouve également derrière l'Italie et la Turquie. La Chine est avec le reste de l'UE et de l'Asie les plus faibles dans le hors-prix. 


